const UserTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_ERROR: "SIGNOUT_ERROR",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
};

export default UserTypes;
